[project]
name = "polish-notation"
version = "0.1.0"
description = "Evaluate polish notation expressions."
requires-python = ">=3.12"
dependencies = [
    "envoi",
]

[tool.uv.sources]
envoi = { path = "../../..", editable = true }
